backend: # Required
  name: git-gateway
  branch: main
media_folder: "src/assets/images" # Required
public_folder: "assets/images" # Required
collections: # Required
  - label: "Pages" # Required. Used in the UI
    name: "pages" # Required. Used in routes
    folder: "src" # Required. The path to the folder where the documents are stored
    create: true # Important. Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # Required. The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} # Required
      - {label: "Layout", name: "layout", widget: "string"}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        options: ["primary", "sidebar", "footer"]
      - {label: "Body", name: "body", widget: "markdown"} # Required
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/links.json"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Decap CMS Elements"
        name: "items"
        file: "src/_data/decap.json"
        fields:
          - label: Elements
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Element, name: element, widget: string }
              - { label: Value, name: value, widget: string }