backend: # Required
  name: git-gateway
  branch: main
media_folder: "src/assets/images" # Required
public_folder: "assets/images" # Required
collections: # Required
  - label: "Pages" # Required. Used in the UI
    name: "pages" # Required. Used in routes
    folder: "src" # Required. The path to the folder where the documents are stored
    create: true # Important. Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # Required. The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} # Required
      - {label: "Layout", name: "layout", widget: "string"}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        options: ["primary", "sidebar", "footer"]
      - {label: "Body", name: "body", widget: "markdown"} # Required
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Decap CMS Elements"
        name: "decap"
        file: "src/_data/decap.json"
        fields:
          - label: "Elements"
            name: "items"
            widget: "list"
            allow_add: true
            collapsed: true
            fields:
              - { label: "Element", name: "element", widget: "string" }
              - { label: "Level", name: "level", widget: "number" }
              - { label: "Required", name: "required", widget: "boolean" }
              - { label: "Value", name: "value", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }